# Generated by Django 5.2.6 on 2025-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.AutoField(db_column='MovieID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='MovieTitle', max_length=200)),
                ('actor1', models.CharField(db_column='Actor1Name', max_length=100)),
                ('actor2', models.CharField(blank=True, db_column='Actor2Name', max_length=100)),
                ('director', models.CharField(db_column='DirectorName', max_length=100)),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Animation', 'Animation'), ('Thriller', 'Thriller'), ('Other', 'Other')], db_column='MovieGenre', max_length=20)),
                ('release_year', models.PositiveIntegerField(db_column='ReleaseYear')),
            ],
            options={
                'db_table': 'Video',
            },
        ),
    ]
