apiVersion: v1
kind: PersistentVolume
metadata:
  name: taskapp-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/taskapp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskapp-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
